### ISSUE TITLE
Adjusting individual instrument/part staff heights

### ISSUE THREAD

**Issue by ryanschiang** [opensheetmusicdisplay/opensheetmusicdisplay#1531]
Hello everyone and thanks for the great library.

I am using OSMD to render sheet music in my React application. I have a score with four instruments: Violin, Viola, Violoncello, and Piano. My goal is to adjust the staff heights of the first three instruments (stringed instruments) to be smaller than the piano staves.

I have tried the following approaches to achieve this:

1. Modifying the MusicXML file: I tried adding the staff-size element within the staff-details element for each part in the MusicXML file, but it had no effect on the rendered output. 
2. Using the EngravingRules: I see that EngravingRules.StaffHeight is available, but this applies to all parts/instruments and I wasn't able to specify this for specific parts only.
3. Applying custom CSS styles: I tried targeting the staves using CSS selectors based on the generated HTML structure, but the OSMD only renders a div and an SVG element without specific groups representing the individual parts.

I also tried iterating over the instruments like so:
```typescript
osmd.Sheet.Instruments.forEach((instrument) => {
    instrument.Staves.forEach((staff) => {
        // Adjust height here?
    })
});
```

But I couldn't find a way to adjust the height from the `Staff` objects.

Unfortunately, none of my approaches have successfully adjusted the staff heights for the individual parts.I would greatly appreciate any suggestions, workarounds, or alternative approaches to adjust the heights of individual staves.

Thank you in advance for your assistance!

**Comment by sschmidTU** [comment]
@ryanschiang I've added SVG groups for stafflines in the latest commit in develop, can you test the SVG scaling method?

<img width="1256" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/e8e2d84f-324d-40a9-ac13-91bae0a94382">

Otherwise unfortunately this is not currently possible and also not easy to implement, as far as I can see. OSMD assumes a uniform staff height in many places in the code.
Also, there might be some elements like lyrics and instrument labels that are not in the staffline group and might also be hard to put in it.

(audio player people note that we already do it similarly in the audio player, will need to merge both versions eventually)

**Comment by ryanschiang** [comment]
@sschmidTU Thanks for such a quick response!

With the SVG groups for staff lines, I was able to use styles to adjust the staff heights using `transform`'s.

While a little bit hacky and not perfect visually (the notes, text, and curves are vertically squished in order to maintain the proper horizontal spacing), this certainly works for my use case.

<img width="762" alt="Screenshot 2024-04-02 at 5 29 32 PM" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/45606922/398d804b-93a8-41a5-89d7-e861f3e83fa1">

And here's my CSS snippet:

```css
#Violin0-1 > .vf-measure > *:not(.vf-clef):not(.vf-keysignature):not(.vf-timesignature) {
  transform: scaleY(var(--scale));
}

#Violin0-1 > .vf-line,
#Violin0-1 > .vf-curve,
#Violin0-1 > .vf-text {
  transform: scaleY(var(--scale));
}

#Violin0-1 > .vf-measure > .vf-keysignature,
#Violin0-1 > .vf-measure > .vf-timesignature,
#Violin0-1 > .vf-measure > .vf-clef {
  transform: scale(var(--scale)) translateX(var(--adjustX));
}
```

Presumably you'd have to tweak the `--scale` and `--adjustX` values accordingly and make these responsive, but given the complexity of implementing a more comprehensive solution, I think this is a well-suited approach for this case.

Thanks again.
